version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/vertx-redis-test
    steps:
      - checkout
      - restore_cache:
          key: vertx-redis-test-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: vertx-redis-test-{{ checksum "pom.xml" }}
      - run: docker run -a stdout -a stderr -w /app -v ${PWD}:/app -v ~/.m2:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock maven mvn test
      - store_test_results:
          path: target/surefire-reports
